welcome_message = "PLEASE READ BEFORE STARTING\n\nHey there !! This is Aura, an Ai Emotion based song recommendation system.🎶\n\nThings to know\n\n1️⃣ Your chat is always engrypted🔒\n\n2️⃣ Do not share any personal information in the chat🚫\n\n3️⃣ Aura needs atleast 5 statements/Inputs from you to analyse your mood\n\n4️⃣ When you type /stop, the chat gets deleted and refreshed\n\n 5️⃣ No more rules, Enjoyyy😎\n"



greeting_list = [
    "hi",
    "hey",
    "heyyy",
    "heyy",
    "heyoooo",
    "ola",
    "hello",
    "yo"
]

response_greet = [
    "Hi there !! How're you ?",
    "Hey, How's Your day been ?",
    "Hello! How can I assist you today?",
    "Hey there! What's new?",
    "Hi, how's everything on your end?",
    "Hello! How's life treating you?",
    "Hey, what's happening?",
    "Hi there! Ready to chat?",
    "Hello, my friend! How can I help you?",
    "Hey, how's the world treating you today?",
    "Hi! How's your day been?",
    "Hello! What's the latest?",
    "Hey there! How are things?",
    "Hi, how can I brighten your day?",
    "Hello! What's on your mind?",
    "Hey, ready to have a great conversation?",
    "Hi there! What's cooking?",
    "Hello, friend! How have you been?",
    "Hey, how's your mood today?",
    "Hi! Tell me, how's life?",
    "Hello! Let's chat about something awesome.",
    "Hey there! What's the good word?",
    "Hi, how's your energy today?",
    "Hello! How's the weather in your world?",
    "Hey, what's the buzz?",
    "Hi there! How's the day treating you so far?",
    "Hello, friend! How can I make your day better?",
    "Hey, how's it going in your neck of the woods?",
    "Hi! What's the scoop?",
    "Hello! How's your week been?",
    "Hey there! Let's have a great conversation.",
    "Hi, what's the 411?",
    "Hello! How's your spirit today?",
    "Hey, how's life treating you?",
    "Hi there! What's cracking?",
    "Hello, friend! How's everything?",
    "Hey, ready to dive into a conversation?",
    "Hi! How's your day unfolding?",
    "Hello! What's the latest and greatest?",
    "Hey there! How's your mojo?",
    "Hi, what's the news?",
    "Hello! How's your vibe today?",
    "Hey, how's the universe in your corner?",
    "Hi there! How's the rhythm of life?",
    "Hello, friend! What's the word on the street?",
    "Hey, how's your day shaping up?",
    "Hi! What's the scoop?",
    "Hello! How's your spark today?",
    "Hey there! How's your aura?",
    "Hi, what's happening in your world?",
    "Hello! How's your enthusiasm?"
]
    
stop_words = [
    "stop",
    "shut up",
    "cease",
    "halt",
    "end",
    "terminate",
    "discontinue",
    "pause",
    "finish",
    "complete",
    "quit"
]

stop_response = [
    "It's okay, I'll stop. Take care!",
    "Alright, I'll stop now. Farewell!",
    "No problem, I'll wrap things up. Goodbye!",
    "Understood, I'll cease our conversation. See you later!",
    "Sure thing, I'll stop here. Until next time!",
    "Got it, I'll end our chat. Bye for now!",
    "Okay, I'll put an end to our discussion. Take care!",
    "Of course, I'll stop talking now. Goodbye!",
    "Certainly, I'll stop. Have a great day!",
    "Noted, I'll finish up. Farewell!",
    "Absolutely, I'll cease. See you soon!",
    "Acknowledged, I'll stop here. Goodbye!",
    "No worries, I'll wrap it up. Take care!",
    "You got it, I'll stop now. Until we meet again!",
    "Gotcha, I'll end our conversation. Bye bye!",
    "Sure, I'll stop talking. Have a wonderful day!",
    "Okay, I'll put a stop to it. Farewell!",
    "Of course, I'll cease our chat. Take care!",
    "Absolutely, I'll stop. Until next time!",
    "Noted, I'll finish the conversation. Goodbye!"
]


sad = [
    "rough day",
    "tired a lot",
    "stress",
    "stressed",
    "feeling down",
    "heartbroken",
    "lonely",
    "unhappy",
    "gloomy",
    "miserable",
    "depressed",
    "sorrowful",
    "tearful",
    "melancholy",
    "disheartened",
    "despondent",
    "hopeless",
    "blue",
    "suffering",
    "painful",
    "troubled",
    "overwhelmed",
    "upset",
    "disappointed",
    "downhearted",
    "angry",
    "anxious",
    "regretful",
    "lost",
    "rejected",
    "isolated",
    "dejected",
    "weary",
    "exhausted",
    "aching",
    "brokenhearted",
    "dismal",
    "mournful",
    "forlorn",
    "downcast",
]


happy = [
    "joyful",
    "happy",
    "excited",
    "ecstatic",
    "elated",
    "euphoric",
    "cheerful",
    "delighted",
    "content",
    "blissful",
    "overjoyed",
    "gleeful",
    "jubilant",
    "exhilarated",
    "upbeat",
    "uplifted",
    "radiant",
    "smiling",
    "laughing",
    "grateful",
    "thankful",
    "satisfied",
    "thrilled",
    "amazing",
    "wonderful",
    "fantastic",
    "awesome",
    "witty",
    "vibrant",
    "blessed",
    "lively",
    "cheery",
    "carefree",
    "hopeful",
    "optimistic",
    "spirited",
    "enjoying",
    "ecstatic",
    "triumphant",
    "playful",
    "charming",
    "merry",
    "jovial",
    "festive",
    "sparkling",
    "heartwarming",
    "exuberant",
]

song_refr = [
    "sugest a song",
    "suggest a song for me",
    "tell me a song",
    "tell mea good song",
    "give me a song",
    "song",
]

last_conv = [
    "last conversation",
    "previously",
    "previous conversation"
]

name_ask = [
    "who are you",
    "your name",
    "what are you"
]